In [3]:
import numpy as np

Is=[[4,1,3],[0,2,6],[7,5,8]]
fs=[[1,2,3],[4,5,6],[7,0,8]]

def manhattan_distance(Is,fs,num):
    Isarray=[]
    fsarray=[]
    for i in range(3):
        for j in range(3):
            if(Is[i][j]==num):
                Isarray=[i,j]
            if(fs[i][j]==num):
                fsarray=[i,j]
    dist=abs(Isarray[0]-fsarray[0])+abs(Isarray[1]-fsarray[1])
    return dist

def possible_ways(Is):
    arr=[]
    for i in range(3):
        for j in range(3):
            if(Is[i][j]==0):
                arr=[i,j]
                break
    routes=[]
    if((arr[0]-1)>=0):
        routes.append([arr[0]-1,arr[1]])
    if(arr[0]+1<3):
        routes.append([arr[0]+1,arr[1]])
    if(arr[1]+1<3):
        routes.append([arr[0],arr[1]+1])
    if(arr[1]-1>=0):
        routes.append([arr[0],arr[1]-1])
    return routes,arr

def solve():
    global Is
    global fs
    move=0
    while(Is!=fs):
        routes,arr=possible_ways(Is)
        current_dist=5000
        best_move=[]
        for i in routes:
            Is[i[0]][i[1]],Is[arr[0]][arr[1]]=Is[arr[0]][arr[1]],Is[i[0]][i[1]]
            sum_dist=0
            for j in range(3):
                for k in range(3):
                    if(Is[j][k]!=0):
                        sum_dist+=manhattan_distance(Is,fs,Is[j][k])
            if(sum_dist<current_dist):
                current_dist=sum_dist
                best_move=i
            Is[i[0]][i[1]],Is[arr[0]][arr[1]]=Is[arr[0]][arr[1]],Is[i[0]][i[1]]
        Is[best_move[0]][best_move[1]],Is[arr[0]][arr[1]]=Is[arr[0]][arr[1]],Is[best_move[0]][best_move[1]]
        move+=1
        print(np.array(Is))
    print(f'moves taken: {move}')
#     return move

In [4]:
solve()

[[0 1 3]
 [4 2 6]
 [7 5 8]]
[[1 0 3]
 [4 2 6]
 [7 5 8]]
[[1 2 3]
 [4 0 6]
 [7 5 8]]
[[1 2 3]
 [4 5 6]
 [7 0 8]]
moves taken: 4
